### ISSUE TITLE
Crash from 'bbs_coloc'

### ISSUE THREAD

**Issue by agnivsen** [shaifaliparashar/rnrsfrm#1]
Thanks for the code. However, code crashes upon running the example Matlab scripts. Please find the description below.

Running _example_fast.m_ causes code to crash with the following error message:

```
Output argument "mat" (and maybe others) not assigned during call to "bbs_coloc".

Error in create_grid (line 26)
        coloc = bbs_coloc(bbs, q_n(1,idx), q_n(2,idx));

Error in example_fast (line 12)
[I1u,I1v,I2u,I2v,~] = create_grid(qg,visb',grid_size);
```

Running _example_robust.m_ causes code to crash with the following error message:

```
Output argument "mat" (and maybe others) not assigned during call to "bbs_coloc".

Error in fix_mad_correspondences (line 23)
            coloc = bbs_coloc(bbs, q{s}(1,idx), q{s}(2,idx));

Error in example_robust (line 13)
[qpn,qpn2,idd,rmv] = fix_mad_correspondences(qp,visb',list); % idd are flagged
points
```

**Environment:** running the code from Matlab version '9.5.0.944444 (R2018b)' on Windows 10 (Intel Core i7-10750H CPU)

Probably a minor issue. Please look into it.

Thanks in advance.

**Comment by shaifaliparashar** [comment]
you need to compile the tolbox i f you are not using ububtu/linux. I'd say: use linux, its much simpler. However, you can download the executable for windows from http://www.brnt.eu/downloads.php#bbs

**Comment by agnivsen** [comment]
This works fine in Ubuntu, thanks a lot.
